[package]
name = "vsop"
version = "0.1.0"
edition = "2021"

[[bin]] # Bin to run the HelloWorld gRPC server
name = "server"
path = "src/server.rs"

[[bin]] # Bin to run the HelloWorld gRPC client
name = "client"
path = "src/client.rs"

[dependencies]
anyhow = "1.0.83"
ct2rs = { path = "../ctranslate2-rs", features = ["accelerate"] }
tempfile = "3.10.1"
clap = { version = "4.5.4", features = ["derive"] }
directories = "5.0.1"
spinners = "4.1.1"
tonic = "0.11.0"
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread"] }
prost = "0.12.4"

[build-dependencies]
tonic-build = "0.11.0"
