name: Build

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-13, macos-14 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install protobuf
        if: runner.os == 'macOS'
        run: brew install protobuf
      - name: Install protobuf
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install libprotobuf-dev protobuf-compiler
      - name: Build
        run: cargo build -vv
      - name: Test
        run: cargo test -vv
